# Generated by Django 3.1.7 on 2021-04-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
