# Generated by Django 3.1.7 on 2021-04-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210429_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated',
            field=models.FloatField(default=0),
        ),
    ]
