# Generated by Django 3.1.7 on 2021-04-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_payments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
