# Generated by Django 3.1.7 on 2021-05-16 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210429_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='name',
            new_name='number',
        ),
    ]
