# Generated by Django 3.1.7 on 2021-05-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210516_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='total_client_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='total_expense',
            field=models.FloatField(default=0),
        ),
    ]
