# Generated by Django 3.1.7 on 2021-05-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210516_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='serial_number',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
