# Generated by Django 3.1.7 on 2021-05-21 09:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(default=0, max_length=50)),
                ('expense_on', models.CharField(max_length=100)),
                ('expense_by', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miscellaneous', to='projects.project')),
            ],
        ),
    ]
