# Generated by Django 3.1.7 on 2021-05-24 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_name', models.CharField(max_length=200)),
                ('contract_type', models.CharField(max_length=200)),
                ('contract_value', models.FloatField()),
                ('variation', models.FloatField(default=0.0)),
                ('total_contract_value', models.FloatField(default=0.0)),
                ('due', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(default='cash', max_length=100)),
                ('amount', models.FloatField()),
                ('amount_due', models.FloatField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract')),
            ],
        ),
    ]
