# Generated by Django 3.1.7 on 2021-05-15 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210429_1504'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='expense',
            new_name='contract_value',
        ),
        migrations.AddField(
            model_name='contract',
            name='total_contract_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='contract',
            name='variation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='projects.project'),
        ),
    ]
