# Generated by Django 3.1.7 on 2021-04-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.CharField(default='mukesh', max_length=200),
            preserve_default=False,
        ),
    ]
