# Generated by Django 3.1.7 on 2021-05-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20210527_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-date']},
        ),
    ]
