# Generated by Django 3.1.7 on 2021-04-12 06:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='due',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('amount_due', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='materials.material')),
            ],
        ),
    ]
