# Generated by Django 3.1.7 on 2021-04-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20210412_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_due',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
