# Generated by Django 3.1.7 on 2021-04-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20210412_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(default='kuch bhi', max_length=200),
            preserve_default=False,
        ),
    ]
