# Generated by Django 3.1.7 on 2021-04-29 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_auto_20210412_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.CharField(default='', max_length=200),
        ),
    ]
