# Generated by Django 3.1.7 on 2021-05-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_auto_20210429_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='name',
            new_name='number',
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(default='cash', max_length=100),
        ),
    ]
