# Generated by Django 3.1.7 on 2021-03-08 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 11, 6, 56, 181912, tzinfo=utc)),
        ),
    ]
