# Generated by Django 3.1.7 on 2021-03-09 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210308_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 7, 11, 35, 152121, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
