# Generated by Django 3.1.7 on 2021-03-09 09:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210309_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 9, 40, 6, 849829, tzinfo=utc)),
        ),
    ]
