# Generated by Django 3.1.7 on 2021-03-10 00:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210310_0557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='c_name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='p_name',
            new_name='project_name',
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 10, 0, 43, 3, 452781, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
            ],
        ),
    ]
