# Generated by Django 3.1.7 on 2021-03-10 00:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210310_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 10, 0, 44, 48, 978529, tzinfo=utc)),
        ),
    ]
