# Generated by Django 3.1.7 on 2021-03-13 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210310_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='accounts.project'),
        ),
    ]
