# Generated by Django 3.1.7 on 2021-04-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='total_pay',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
