# Generated by Django 3.1.7 on 2021-04-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labours', '0002_labour_total_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='total_pay',
            field=models.FloatField(default=0),
        ),
    ]
