# Generated by Django 3.1.7 on 2021-05-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labours', '0003_auto_20210416_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='name',
            new_name='number',
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(blank=True, default='cash', max_length=100, null=True),
        ),
    ]
